title:             M A E M I
email:             maemi.js@gmail.com
description:       blog, portfolio, books, music etc.
author:            maemi
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://maeeemi.github.io"

# Social Profiles
twitter_username:  maeeemi
github_username:   maeeemi
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

remote_theme : BlackrockDigital/startbootstrap-clean-blog-jekyll
